### ISSUE TITLE
Send benchmark reports to Slack

### ISSUE THREAD

**Issue by axw** [elastic/hey-apm#170]
Push reports to Slack, to keep them front of mind.

**Comment by cachedout** [comment]
Hi @axw . Apologies for letting this one fall through the cracks. Which channel would you like these sent to and at what frequency?

**Comment by axw** [comment]
@cachedout no worries. Weekly to #apm-server would be good to start with, then we reassess later.

One thing to note is that I'm developing a proposal to replace hey-apm and subsequently the dashboards we have.
Is it fair to assume that we will be able to easily change which dashboard will be shared if we do that?

**Comment by cachedout** [comment]
## Tasks

- [x] Request Slack webhook from infra
- [ ] [Configure Slack action in ES](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/actions-slack.html)
- [ ] [Automate report generation](https://www.elastic.co/guide/en/kibana/current/automating-report-generation.html)

**Comment by cachedout** [comment]
Done and deployed. This should run once a week from this point forward.

The automation which drives this report is in a private repo so I won't link to it here but am happy to answer questions on implementation details in that repo or via Slack. Thanks!
