### ISSUE TITLE
Support intake-v2 in hey apm

### ISSUE THREAD

**Issue by jalvz** [elastic/hey-apm#32]
- [x] Support non streaming interactive and non interactive mode: https://github.com/elastic/hey-apm/pull/51

- [ ] Shuffle events in V2 composer: https://github.com/elastic/hey-apm/issues/54

- [ ] Update/Fix `desc` and `dump` cmd line options: https://github.com/elastic/hey-apm/issues/53

- [x] Support streaming interactive mode: https://github.com/elastic/hey-apm/issues/55

- [ ] Ensure that calculations are correct for streaming and not streaming: https://github.com/elastic/hey-apm/issues/58

- [ ] Update CI https://github.com/elastic/hey-apm/issues/56

**Comment by jalvz** [comment]
@graphaelli @roncohen  opened this for tracking

**Comment by simitt** [comment]
@juan how about moving this back to backlog? I think the most critical parts for v2 testing are done, and I'd see the others as nice to have.
