### ISSUE TITLE
Refactor to fit better the cloud testing use case

### ISSUE THREAD

**Issue by jalvz** [elastic/hey-apm#91]
- [x] Remove functionality with little value (eg. building docker images) and making big issue of shell commands
- [x] Unify packages, simplify interface and operations
- [x] Have 2 layers of functions: bottom layer returns data, top layer displays it
- [ ] Query / filter by labels work
- [x] Update documentation

**Comment by jalvz** [comment]
lets be done with refactoring for now...
